### ISSUE TITLE
JTOGAF#1: register website domain

### ISSUE THREAD

**Issue by joseosuna** [jtogaf/jtogaf#1]
# Details
**Story Points:** 6 points.

# Description
register website domain.

**User:** All website users.
**I Want:** the project has a website.
**In order to:** show project and product deploys.

**Criteria:**
1. Click URL http://jtogaf.com and can use domain.

**Examples:**
http://jtogaf.com

# Sub-Tasks
1. [x] [JTOGAF#2: register a web email.] (https://github.com/jtogaf/jtogaf/issues/2)
2. [x] [JTOGAF#3: create a domain register account.] (https://github.com/jtogaf/jtogaf/issues/3)
3. [x] [JTOGAF#4: reserve the domain.] (https://github.com/jtogaf/jtogaf/issues/4)
4. [x] [JTOGAF#5: create a DNS hosting account.] (https://github.com/jtogaf/jtogaf/issues/5)
5. [x] [JTOGAF#6: create an email hosting account.] (https://github.com/jtogaf/jtogaf/issues/6)
6. [x] [JTOGAF#7: configure dmarc email services.] (https://github.com/jtogaf/jtogaf/issues/7)

# Time Tracking
**Date Started:** May 04, 2015.
**Time Spent:** *(eg. 3w 4d 12h)* 3h.
