### ISSUE TITLE
JTOGAF#9: deploy 'www' host

### ISSUE THREAD

**Issue by joseosuna** [jtogaf/jtogaf#9]
# Details

**Story Points:**  1 point.
# Description

We need a home host. Our host most be located in http://www.jtogaf.com.
http://jtogaf.com must be redirected to http://www.jtogaf.com.

**User:** All users.
**I Want:** Know the principal website page.
**In order to:** access the website.

**Criteria:**
1. Write URI in a browser and verify host is enabled.

**Examples:**
http://www.jtogaf.com. 
http://jtogaf.com. 
# Issue Links

This issue clones:
[RSTATIC#1: deploy 'rstatic' host](https://github.com/reddepruebas/rstatic/issues/1)
# Sub-Tasks
1. [x] [JTOGAF#8: Create a Jboss 7.1 engine in OpenShift.](https://github.com/jtogaf/jtogaf/issues/8)
2. [x] [JTOGAF#10: Add both alias in Open Shift.](https://github.com/jtogaf/jtogaf/issues/10)
3. [x] [JTOGAF#11: Add a CNAME and redirect in DNS hosting.](https://github.com/jtogaf/jtogaf/issues/11)
4. [ ] [JTOGAF#12: Clone Open Shift Project.](https://github.com/jtogaf/jtogaf/issues/12)
5. [ ] [JTOGAF#13: Load project page full HTML META TAGS.](https://github.com/jtogaf/jtogaf/issues/13)
6. [ ] [JTOGAF#14: Link code to GitHub.](https://github.com/jtogaf/jtogaf/issues/14)
# Time Tracking

**Date Started:** May 05, 2015.
**Time Spent:** _(eg. 3w 4d 12h)_ 30m.
